spring.application.name=banking-app

# JPA 
spring.datasource.url=jdbc:mysql://localhost:9090/banking_app
spring.datasource.username=root
spring.datasource.password=Maku@apsoft!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server Port
server.port=8099