spring.application.name=banking-app

# JPA 
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server Port
server.port=${SERVER_PORT:8099}

#SLF4J API + LOGBACK
logging.level.root=INFO
logging.file.name=logs/app.log